# This is a basic workflow to help you get started with Actions

name: Nuitka compile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      # https://github.com/actions/setup-python
      - name: Use Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      # Runs a single command using the runners shell
      - name: Install Nuitka
        run: python -m pip install nuitka

      - name: Compile with Nuitka
        run: python -m nuitka --standalone --python-flag=no_site --plugin-enable=tk-inter --windows-icon-from-ico=assets\sun_white.ico --assume-yes-for-downloads ${{ github.workspace }}\main_tk.py

      - name: Store dist
        uses: actions/upload-artifact@v2
        with:
          name: screen_on_release
          path: ${{ github.workspace }}\main_tk.dist
